name: CI/CD for Full Stack App

# Controls when the action will run.
on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      job_name:
        description: 'Run Job'
        required: true
        default: 'build_test'

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Frontend build and test
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Npm Packages
        run: npm install
        working-directory: frontend
        
      - name: Test React App
        run: npm test -- --watchAll=false
        working-directory: frontend
          
      - name: Build React App
        run: npm run build
        working-directory: frontend

      # Backend build and test
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
          
      - name: Install and Build Backend
        run: mvn clean install
        working-directory: backend

      - name: Test Backend
        run: mvn test
        working-directory: backend
